
showSubscribe = true
title = "The world as a stage"
subtitle = ""

cover = ""
description = ""
metaDescription = ""
googleAnalytics = "UA-37300513-2"
customCSS = ["overrides.css", "syntax.css"]
RSSLink = ""

twitterName = "nicotupe"
fbName = "nicotupe"
githubName = "bcoulange"
goodreadsName = "nicotupe"
linkedinName = 'baptiste-coulange'
mediumName = 'nicotupe'

logo = ""
orgName = "Nicotupe"
orgWebsite = ""
orgDescription = ""

author = "Baptiste Coulange"
authorAvatar = "img/avatar-festiblog.jpg"
authorLocation = "Barcelona, Spain"
authorWebsite = ""
authorDescription = "CTO at @cornis_SAS / socially acceptable maths nerd of @podcastscience / always improvising"

pageNotFoundTitle = "404 - Page not found"


# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

showComments = true

autoSwitchAppearance = true
colorScheme = "Noir"
enableSearch = true
enableCodeCopy = true

mainSections = ["post"]
# robots = ""

disableImageOptimization = false
disableTextInHeader = false

# defaultBackgroundImage = "/img/ocean.jpg"
# defaultFeaturedImage = "/img/ocean.jpg"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

[header]
layout = "fixed" # valid options: basic, fixed, fixed-fill, fixed-fill-blur

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true


[homepage]
layout = "background" # valid options: page, profile, hero, card, background, custom
homepageImage = ""    # used in: hero, and card
showRecent = true
showRecentItems = 12
showMoreLink = true
# showMoreLinkDest = "posts"
cardView = false
cardViewScreenWidth = false
layoutBackgroundBlur = true # only used when layout equals background


[article]
showDate = false
showViews = false
showLikes = false
showDateUpdated = false
showAuthor = true
showHero = true
heroStyle = "background"                                  # valid options: basic, big, background, thumbAndBackground
layoutBackgroundBlur = true                               # only used when heroStyle equals background
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showRelatedContent = true
relatedContentLimit = 6
showTaxonomies = true
showAuthorsBadges = true
showWordCount = false
sharingLinks = ["twitter", "reddit", "whatsapp", "email"]

[list]
showHero = true
heroStyle = "background"            # valid options: basic, big, background, thumbAndBackground
layoutBackgroundBlur = true         # only used when heroStyle equals background
layoutBackgroundHeaderSpace = false
showBreadcrumbs = false
showSummary = true
showViews = false
showLikes = false
showTableOfContents = true
showCards = true
groupByYear = false
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = []

[taxonomy]
showTermCount = true
showHero = true
heroStyle = "background"   # valid options: basic, big, background, thumbAndBackground
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
cardView = false

[term]
showHero = true
heroStyle = "background"    # valid options: basic, big, background, thumbAndBackground
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = true
cardViewScreenWidth = false

[firebase]
apiKey = "AIzaSyB5tqlqDky77Vb4Tc4apiHV4hRZI18KGiY"
authDomain = "blowfish-21fff.firebaseapp.com"
projectId = "blowfish-21fff"
storageBucket = "blowfish-21fff.appspot.com"
messagingSenderId = "60108104191"
appId = "1:60108104191:web:039842ebe1370698b487ca"
measurementId = "G-PEDMYR1V0K"

[fathomAnalytics]
# site = "ABC12345"
# domain = "llama.yoursite.com"

# [buymeacoffee]
# identifier = "nunocoracao"
# globalWidget = true
# globalWidgetMessage = ""
# globalWidgetColor = "#FFDD00"
# globalWidgetPosition = "Right"

[verification]
# google = ""
# bing = ""
# pinterest = ""
# yandex = ""
