baseURL = "https://theworldasastage.github.io/hugo/"
theme           = "casper-two"
languageCode = "en-us"
disqusShortname = "the-world-as-a-stage"
paginate        = 6
title = "The world as a stage"

googleAnalytics = "UA-37300513-2"


# SectionPagesMenu = "main"
rssLimit = 15
pygmentsUseClassic=false
pygmentsCodefences=true
pygmentsUseClasses=true

publishDir = "docs"

[params]
  showSubscribe = true
  title       = "The world as a stage"
  subtitle    = "Improvisation - Remote working - Relationships - Culture"

  cover       = ""
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = "UA-37300513-2"
  customCSS = ["overrides.css","syntax.css"]
  RSSLink = ""

  twitterName = "nicotupe"
  fbName = "nicotupe"
  githubName = "bcoulange"
  goodreadsName = "nicotupe"
  linkedinName = 'baptiste-coulange'
  mediumName = 'nicotupe'

  logo = ""
  orgName = "Nicotupe"
  orgWebsite = ""
  orgDescription = ""

  author = "Baptiste Coulange"
  authorAvatar = "img/avatar-tupe-chaplin.jpg"
  authorLocation = "Barcelona, Spain"
  authorWebsite = ""
  authorDescription = "Remote CTO at @cornis_SAS / socially acceptable maths nerd of @podcastscience / always improvising"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "About me"
  url = "/about/"
  weight = 99

[[menu.main]]
  name = "Reading list"
  url = "/reading-list/"
  weight = 98


[[menu.main]]
  name = "Improvisation"
  url = "/categories/improvisation/"
  weight = 97

[[menu.main]]
  name = "Science"
  url = "/categories/science/"
  weight = 97

# [[menu.main]]
#   name = "Podcast"
#   url = "/tags/podcast/"
#   weight = 99
