baseURL = "https://theworldasastage.github.io/hugo/"
theme           = "casper-two"
languageCode = "en-us"
disqusShortname = "the-world-as-a-stage"
paginate        = 6
title = "The world as a stage"

# SectionPagesMenu = "main"
rssLimit = 15
pygmentsUseClassic=false
pygmentsCodefences=true
pygmentsUseClasses=true

publishDir = "docs"

[params]
  title       = "The world as a stage"
  subtitle    = ""

  cover       = ""
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = ["overrides.css","syntax.css"]
  RSSLink = ""

  twitterName = "nicotupe"
  fbName = "nicotupe"
  githubName = "bcoulange"

  logo = ""
  orgName = "Nicotupe"
  orgWebsite = ""
  orgDescription = ""

  author = "Baptiste Coulange"
  authorAvatar = "img/avatar-tupe-chaplin.jpg"
  authorLocation = "Barcelona, Spain"
  authorWebsite = ""
  authorDescription = "Remote CTO at @cornis_SAS / socially acceptable maths nerd of @podcastscience / always improvising"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Improvisation"
  url = "/categories/improvisation/"
  weight = 99

[[menu.main]]
  name = "Science"
  url = "/categories/science/"
  weight = 99

[[menu.main]]
  name = "Podcast"
  url = "/tags/podcast/"
  weight = 99
